version: '3'

services:
  web:
    build: .
    ports:
      - "10000:10000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=your_session_secret_here
      - STRIPE_SECRET_KEY
      - VITE_STRIPE_PUBLIC_KEY