services:
  - type: web
    name: blue-whale-competitions
    env: docker
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false # Will be manually set
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false # Will be manually set
      - key: DATABASE_URL
        fromDatabase:
          name: blue-whale-db
          property: connectionString

databases:
  - name: blue-whale-db
    plan: free # Use free tier for initial setup, can be upgraded later