services:
  - type: web
    name: blue-whale-competitions
    plan: starter
    env: node
    runtime: node
    nodeVersion: 20.11.1
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /