services:
  - type: web
    name: blue-whale-competitions
    env: node
    plan: starter
    buildCommand: bash ./render-install.sh && npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist
    startCommand: node server-docker.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false # Will be manually set
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false # Will be manually set
      # Add SSL requirement to the database connection
      - key: DATABASE_URL
        fromDatabase:
          name: blue-whale-db
          property: connectionString
        previewValue: postgres://postgres:postgres@postgres:5432/postgres?sslmode=require
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: blue-whale-db
    plan: free # Use free tier for initial setup, can be upgraded later