services:
  - type: web
    name: blue-whale-competitions
    plan: starter
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: VITE_STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /